### PR TITLE
feat(shulker-operator): add the possibility to use custom server jars

### LINKED ISSUE #253: Add the possibility to use custom server jars
### Discussed in https://github.com/jeremylvln/Shulker/discussions/252

<div type='discussions-op-text'>

<sup>Originally posted by **TropicLegend** November 30, 2023</sup>
It would be very beneficial to have the ability to use custom server jars since only paper or folia feels limiting</div>

### PR DESCRIPTION
**Pull request by jeremylvln**
Closes #252
Closes #253

### CODE REVIEW

**Comment by TropicLegend** [comment]
> Hi @TropicLegend, the custom server JAR feature should work, I do not have the time to test it tonight but will do tomorrow :)

Oh w ow  that was fast. I will  try it out later today. Thank  you!

**Comment by TropicLegend** [comment]
I uninstalled the shulker instance  that was there before.
Then I downloaded the git repository and installed shulker  through helm again.
Unfortunately if I try to use a customJar I get this error:
```
error: error validating "minecraft-server-fleet.yaml": error validating data: ValidationError(MinecraftServerFleet.spec.template.spec.version): unknown field "customJar" in io.shulkermc.v1alpha1.MinecraftServerFleet.spec.template.spec.version; if you choose to ignore these errors, turn validation off with --validate=false
```
My  Config:
```
apiVersion: shulkermc.io/v1alpha1
kind: MinecraftServerFleet
metadata:
  name: ca-server
  namespace: minecraft-network
spec:
  clusterRef:
    name: fl-net
  replicas: 1
  template:
    spec:
      podOverrides:
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2048Mi"
            cpu: "4000m"
      clusterRef:
        name: fl-net
      tags:
        - lobby
      version:
        channel: Paper
        name: '1.20.2'
        customJar:
         - url: https://cloud.xxxx.de/s/oeebb6PjkDZiX3c/download/asp-server.jar
      config:
        plugins:
          - url: https://cloud.xxxx.de/s/fCn6TWGQfaHcMnz/download/EssentialsX-2.20.1.jar
          - url: https://cloud.xxxx.de/s/HjdfDzpgGAjRw9r/download/Chunky-1.3.92.jar
          - url: https://cloud.xxxx.de/s/KX5GoWBpAjSMXj2/download/plugin-1.20.2-R0.1-SNAPSHOT%20-%20Advanced%20Slime%20Paper.jar
```

**Comment by TropicLegend** [comment]
Ooh, I just saw there is another branch I think: https://github.com/jeremylvln/Shulker/tree/feat/253-add-the-possibility-to-use-custom-server-jars

The code was probably only committed there.
I will try again using that branch.

**Comment by TropicLegend** [comment]
> > @jeremylvln Could there possibly be a reason why it does not work for me?
> 
> There is no auto-build on the pull requests, if you want to test this specific code you'll have to build & publish yourself the image. I did not had the time to merge it (so you'll be able to test), but I will do hopefully today :)

ah, okay. I was not aware of that. Thank you!
Then I will wait until the build is released :D 
Just so I know for the future, how to build the image?

**Comment by jeremylvln** [comment]
> > > @jeremylvln Could there possibly be a reason why it does not work for me?
> > 
> > 
> > There is no auto-build on the pull requests, if you want to test this specific code you'll have to build & publish yourself the image. I did not had the time to merge it (so you'll be able to test), but I will do hopefully today :)
> 
> ah, okay. I was not aware of that. Thank you! Then I will wait until the build is released :D Just so I know for the future, how to build the image?

Its a bit overcomplicated to build it haha, I definitely need to smooth that.

By the way, I just tested this PR and everything works, so I'll merge it. I'll release after the volume issue. Until then, you can set the `image.tag` Helm value for the controller to `next` so it will use the latest build :)

**Comment by TropicLegend** [comment]
> > > > @jeremylvln Could there possibly be a reason why it does not work for me?
> 
> > > 
> 
> > > 
> 
> > > There is no auto-build on the pull requests, if you want to test this specific code you'll have to build & publish yourself the image. I did not had the time to merge it (so you'll be able to test), but I will do hopefully today :)
> 
> > 
> 
> > ah, okay. I was not aware of that. Thank you! Then I will wait until the build is released :D Just so I know for the future, how to build the image?
> 
> 
> 
> Its a bit overcomplicated to build it haha, I definitely need to smooth that.
> 
> 
> 
> By the way, I just tested this PR and everything works, so I'll merge it. I'll release after the volume issue. Until then, you can set the `image.tag` Helm value for the controller to `next` so it will use the latest build :)

Using the "next" release, the customJar also works for me. 
Thank you very much 👍.

**Pull request merged**
