### PR TITLE
docs: fix Mincraft typo

### PR DESCRIPTION
**Pull request by risograph**
Fixes typo in section "A Spoon of MinecraftCluster." "Min"craft to Minecraft

### CODE REVIEW

**Review by Rigner — APPROVED** [review]
👍

**Comment by jeremylvln** [comment]
Nice catch! Thanks you!

**Comment by jeremylvln** [comment]
Hi @risograph, thanks again. Would you be able to also modify the same file in the `next` folder? I usually copy the `next` folder into `latest` (you could not find out, it's not documented). If not, your change will be overridden upon next release :(

**Comment by jeremylvln** [comment]
Many thanks @risograph! It should be live in few minutes :)

**Pull request merged**
