### PR TITLE
refactor: migrate to Rust

### PR DESCRIPTION
**Pull request by jeremylvln**

### CODE REVIEW

**Comment by kanya-approve** [comment]
@jeremylvln - this might have broken kube deploy on main

**Comment by jeremylvln** [comment]
> @jeremylvln - this might have broken kube deploy on main...have to manually add minecraftserverfleets crd to resolve
> 
> ```1.6969581663373878e+09	ERROR	setup	unable to create controller	{"controller": "MinecraftServerFleet", "error": "no matches for kind \"MinecraftServerFleet\" in version \"shulkermc.io/v1alpha1\""}```

I've not published anything yet, it's weird that you encounter an issue. Except if you run Shulker from the repository directly. But I will look into that shorty.

**Comment by kanya-approve** [comment]
I run Shulker directly

**Comment by jeremylvln** [comment]
> I run Shulker directly

It was indeed broken. The last commits make the `getting-started` example work. I will see for the other examples soon :)

**Pull request merged**
